# Do not modify this file!  It was generated by ‘nixos-generate-config’
# and may be overwritten by future invocations.  Please make changes
# to /etc/nixos/configuration.nix instead.
{
  config,
  lib,
  modulesPath,
  ...
}:

{
  imports = [
    (modulesPath + "/installer/scan/not-detected.nix")
  ];

  boot.initrd.availableKernelModules = [
    "xhci_pci"
    "ahci"
    "nvme"
    "usbhid"
    "usb_storage"
    "sd_mod"
  ];
  boot.kernelParams = [ "systemd.watchdog_dev=none" ];
  boot.blacklistedKernelModules = [ "iTCO_wdt" ];
  boot.initrd.kernelModules = [
    "nvme"
    "btrfs"
    "usbhid"
    "zram"
  ];
  boot.kernelModules = [
    "nvidia"
    "nvidia_modsetf"
    "nvidia_uvm"
  ];
  boot.extraModulePackages = [ ];

  fileSystems."/" = {
    device = "/dev/disk/by-uuid/ae82fd0c-09e2-4679-b3d3-4ca06b6c5846";
    fsType = "btrfs";
  };

  fileSystems."/mnt/storage" = {
    device = "UUID=695be6a7-1b77-4e63-81c9-64259e239e28";
    fsType = "ext4";
  };

  fileSystems."/boot" = {
    device = "/dev/disk/by-uuid/F24C-3900";
    fsType = "vfat";
    options = [
      "fmask=0077"
      "dmask=0077"
    ];
  };

  swapDevices = [
    { device = "/dev/disk/by-uuid/49724215-0b55-43e7-8406-7b35a26aaad5"; }
  ];

  # Enables DHCP on each ethernet and wireless interface. In case of scripted networking
  # (the default) this is the recommended approach. When using systemd-networkd it's
  # still possible to use this option, but it's recommended to use it in conjunction
  # with explicit per-interface declarations with `networking.interfaces.<interface>.useDHCP`.
  networking.useDHCP = lib.mkDefault true;
  networking.dhcpcd.extraConfig = ''
    nohook resolv.conf
  '';
  # networking.interfaces.eno1.useDHCP = lib.mkDefault true;

  nixpkgs.hostPlatform = lib.mkDefault "x86_64-linux";
  hardware.cpu.intel.updateMicrocode = lib.mkDefault config.hardware.enableRedistributableFirmware;
}
