{
  imports = [
    ./options.nix
    ./secrets.nix
    ./audio.nix
    ./boot.nix
    ./dconf.nix
    ./env.nix
    ./hardware.nix
    ./home-manager.nix
    ./programs.nix
    ./steam.nix
    ./udev.nix
    ./users.nix
    ./wayland.nix
    ./xserver.nix
    ./wms/awesome.nix
    ./dms/lightdm.nix
    ./zram.nix
    ./networking.nix
    ./virtualization.nix
    ./nix-ld.nix
    ./security.nix

    ./services/dnscrypt.nix
    ./services/libinput.nix
    ./services/logind.nix
    ./services/openssh.nix
    ./services/picom.nix
    ./services/sing.nix
  ];
}
