{ pkgs, ... }:
{
  programs.nix-ld.enable = true;
  programs.nix-ld.libraries = with pkgs; [
    gcc
    libgcc
    wineWow64Packages.full
    glibc
    libGL
    freetype
    gnutls
    krb5
    samba
    libx11
    libcap
    cups
    gettext
    dbus
    cairo
    unixodbc
    samba4
    ncurses
    libva
    libpcap
    libv4l
    sane-backends
    libgphoto2
    libkrb5
    fontconfig
    alsa-lib
    libxinerama
    udev
    vulkan-loader
    SDL2
    libusb1
    gst_all_1.gstreamer
    gst_all_1.gst-plugins-base
    gst_all_1.gst-plugins-good
    gst_all_1.gst-plugins-ugly
    gst_all_1.gst-libav
    gst_all_1.gst-plugins-bad
    gtk3
    glib
    opencl-headers
    ocl-icd
    openssl
    libGLU
    mesa
    libdrm
    libxcomposite
    libxcursor
    libxext
    libxfixes
    libxi
    libxrandr
    libxrender
    libxxf86vm
  ];
}
