_: {
  xdg.configFile."enhancer-for-youtube/enchancer_for_youtuve.json" = {
    force = true;
    text = ''
      {
        "version": "2.0.128",
        "settings": {
          "blur": 0,
          "brightness": 100,
          "contrast": 100,
          "grayscale": 0,
          "huerotate": 0,
          "invert": 0,
          "saturate": 100,
          "sepia": 0,
          "applyvideofilters": false,
          "backgroundcolor": "#000000",
          "backgroundopacity": 85,
          "blackbars": false,
          "blockautoplay": true,
          "blockhfrformats": false,
          "blockwebmformats": false,
          "boostvolume": false,
          "cinemamode": false,
          "cinemamodewideplayer": false,
          "controlbar": {
            "active": true,
            "autohide": false,
            "centered": true,
            "position": "absolute"
          },
          "controls": [
            "speed",
            "options"
          ],
          "controlsvisible": false,
          "controlspeed": true,
          "controlspeedmousebutton": false,
          "controlvolume": false,
          "controlvolumemousebutton": false,
          "convertshorts": false,
          "customcolors": {
            "--main-color": "#00adee",
            "--main-background": "#0c0c0c",
            "--second-background": "#111111",
            "--hover-background": "#111111",
            "--main-text": "#eff0f1",
            "--dimmer-text": "#cccccc",
            "--shadow": "#0c0c0c"
          },
          "customcssrules": "",
          "customscript": "",
          "customtheme": false,
          "darktheme": true,
          "date": 1705214519992,
          "defaultvolume": false,
          "disableautoplay": false,
          "executescript": false,
          "expanddescription": false,
          "filter": "none",
          "hidecardsendscreens": false,
          "hidechat": false,
          "hidecomments": false,
          "hiderelated": false,
          "hideshorts": false,
          "ignoreplaylists": true,
          "ignorepopupplayer": true,
          "localecode": "en_US",
          "localedir": "ltr",
          "message": false,
          "miniplayer": true,
          "miniplayerposition": "_top-left",
          "miniplayersize": "_400x225",
          "newestcomments": false,
          "overridespeeds": true,
          "pauseforegroundtab": false,
          "pausevideos": true,
          "popuplayersize": "640x360",
          "qualityembeds": "hd1440",
          "qualityembedsfullscreen": "hd1080",
          "qualityplaylists": "hd1440",
          "qualityplaylistsfullscreen": "hd1080",
          "qualityvideos": "hd1440",
          "qualityvideosfullscreen": "hd1080",
          "reload": false,
          "reversemousewheeldirection": false,
          "selectquality": true,
          "selectqualityfullscreenoff": false,
          "selectqualityfullscreenon": false,
          "speed": 2.8,
          "speedvariation": 0.1,
          "stopvideos": false,
          "theatermode": false,
          "theme": "youtube-deep-dark-custom",
          "themevariant": "youtube-deep-dark.css",
          "update": 1718965868769,
          "volume": 50,
          "volumemultiplier": 3,
          "volumevariation": 5,
          "wideplayer": false,
          "wideplayerviewport": false
        }
      }
    '';
  };
}
